#ifndef FIRSTMODULE_GLOBAL_H
#define FIRSTMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FIRSTMODULE_LIBRARY)
#  define FIRSTMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FIRSTMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FIRSTMODULE_GLOBAL_H
