#ifndef RPCCTRLPLUGIN_GLOBAL_H
#define RPCCTRLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RPCCTRLPLUGIN_LIBRARY)
#  define RPCCTRLPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RPCCTRLPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RPCCTRLPLUGIN_GLOBAL_H
