#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#export LD_LIBRARY_PATH=$OPENSHIFT_REPO_DIR/diy/glibc-2.14/lib:$OPENSHIFT_REPO_DIR/diy/lib
#export QT_PLUGIN_PATH=/var/lib/openshift/5217389c4382ec6aca0000a6/app-root/repo/diy/qtplugins/
cd $OPENSHIFT_DIY_DIR/BGMRPC
echo -e "==== Server start at `date` ====" >> $OPENSHIFT_DIY_DIR/logs/server.log
nohup BGMRServer -a$OPENSHIFT_DIY_IP -p$OPENSHIFT_DIY_PORT -s first.ini >> $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

