#ifndef MISSINGOBJECTHANDLER_GLOBAL_H
#define MISSINGOBJECTHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MISSINGOBJECTHANDLER_LIBRARY)
#define MISSINGOBJECTHANDLER_EXPORT Q_DECL_EXPORT
#else
#define MISSINGOBJECTHANDLER_EXPORT Q_DECL_IMPORT
#endif

#endif  // MISSINGOBJECTHANDLER_GLOBAL_H
