#ifndef RPCFILEPLUGIN_GLOBAL_H
#define RPCFILEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RPCFILEPLUGIN_LIBRARY)
#  define RPCFILEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RPCFILEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RPCFILEPLUGIN_GLOBAL_H
