#ifndef THREADOBJECTINTERFACE_GLOBAL_H
#define THREADOBJECTINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THREADOBJECTINTERFACE_LIBRARY)
#define THREADOBJECTINTERFACE_EXPORT Q_DECL_EXPORT
#else
#define THREADOBJECTINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // THREADOBJECTINTERFACE_GLOBAL_H
