#ifndef OBJECTINTERFACE_H_GLOBAL_H
#define OBJECTINTERFACE_H_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJECTINTERFACE_LIBRARY)
#  define OBJECTINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define OBJECTINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJECTINTERFACE_H_GLOBAL_H
