#ifndef BGMRPCINTERFACE_GLOBAL_H
#define BGMRPCINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BGMRPCINTERFACE_LIBRARY)
#  define BGMRPCINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define BGMRPCINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BGMRPCINTERFACE_GLOBAL_H
