#ifndef PYTHONINTERFACE_GLOBAL_H
#define PYTHONINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PYTHONINTERFACE_LIBRARY)
#  define PYTHONINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define PYTHONINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PYTHONINTERFACE_GLOBAL_H
